apiVersion: v1
kind: Service
metadata:
  name: janni-web-service
spec:
  type: NodePort
  selector:
    app: website # Das verbindet den Service mit deinen Pods/Deployments
  ports:
    - protocol: TCP
      port: 80         # Der Port im Cluster-Netzwerk
      targetPort: 80   # Der Port, den dein Container nutzt
      nodePort: 30080  # Dein "Eingang" von Windows aus